"""
# This file is automatically generated by the build script.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
"""

ROOT = "..."

SRCS = [
    "...",
    "...",
    "...",
]

HDRS = [
    "...",
    "...",
    "...",
]

INCLUDES = [
    "...",
    "...",
    "...",
]
