name: lint
on:
    pull_request:
        branches:
            - trunk
    push:
        branches:
            - trunk
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install Lint Dependencies
              run: pip install -r requirements/lint.txt

            - name: Run flake8
              run: python -m flake8
